version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      # Check for updates to github actions every day
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      # Check for updates to cargo every day
      interval: daily