name: 'Markdown Checker'
description: 'Checks markdown files for broken links and style issues'
author: 'eugenescodes'

inputs:
  files:
    description: 'Files or patterns to check'
    required: false 
    default: '**.md'
  skip_links:
    description: 'Skip link checking'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install md-check
      shell: bash
      run: |
        cargo install --git https://github.com/eugenescodes/md-check

    - name: Check Markdown files
      shell: bash
      env:
        GITHUB_ACTIONS: "true"
      run: |
        # Enable debug output and immediate output flushing
        set -x
        
        if [[ "${{ inputs.skip_links }}" == "true" ]]; then
          stdbuf -o0 find . -name "${{ inputs.files }}" -type f -exec md-check --skip-links {} \;
        else
          stdbuf -o0 find . -name "${{ inputs.files }}" -type f -exec md-check {} \;
        fi