name: Markdown Checker
permissions:
  contents: read
  # pull-requests: write

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run clippy (Rust linter)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Install md-check
        run: |
          # cargo install --git https://github.com/eugenescodes/md-check
          cargo install --path .

      - name: Check Markdown files
        run: |
          find . -name "*.md" -type f -exec md-check lint {} \;
