name: Markdown Checker

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install markdown-tool
        run: |
          cargo install --git https://github.com/eugenescodes/markdown-tool

      - name: Check Markdown files
        run: |
          find . -name "*.md" -type f -exec markdown-tool lint {} \;
